var MSG = {
  title: "BIPES", // 专有名称保留
  blocks: "积木块", // Blockly标准译法，替代原“块”更易理解
  files: "文件",
  shared: "共享",
  device: "设备",
  linkTooltip: "保存积木块并生成分享链接。",
  runTooltip: "运行工作区中积木块定义的程序。",
  badCode: "程序错误：\n%1",
  timeout: "超出最大执行行数限制。",
  trashTooltip: "清空所有积木块。",
  catLogic: "逻辑",
  catLoops: "循环",
  catMath: "数学",
  catText: "文本",
  catLists: "列表",
  catColour: "颜色",
  catVariables: "变量",
  catFunctions: "函数",
  listVariable: "列表",
  textVariable: "文本",
  httpRequestError: "请求处理异常。",
  linkAlert: "通过以下链接分享您的积木块：\n\n%1",
  hashError: "抱歉，没有找到与'%1'对应的已保存程序。",
  xmlError: "无法加载保存的文件。该文件是否由其他版本的Blockly创建？",
  badXml: "XML解析错误：\n%1\n\n选择“确定”放弃对XML的修改，或选择“取消”继续编辑XML。",
  saveTooltip: "将积木块保存到文件。",
  loadTooltip: "从文件加载积木块。",
  notificationTooltip: "通知面板。",
  ErrorGET: "无法加载请求的文件。",
  invalidDevice: "无效设备。",
  languageTooltip: "切换界面语言。",
  noToolbox: "该设备未配置工具箱。",
  networkTooltip: "通过网络连接（WebREPL、HTTP协议）。",
  serialTooltip: "通过串口/USB或蓝牙连接（Web Serial API，基于HTTPS）。",
  toolbarTooltip: "显示工具栏",
  wrongDevicePin: "请检查引脚配置，目标设备已变更！",
  notDefined: "未定义",
  editAsFileValue: "以文件形式编辑",
  editAsFileTooltip: "编辑Python代码并保存到设备文件系统。",
  forumTooltip: "帮助论坛。",
  accountTooltip: "您的项目与设置。",
  blocksLoadedFromFile: "已从文件'%1'加载积木块。",
  deviceUnavailable: "设备'%1'不可用。",
  notConnected: "无可用连接用于发送数据。",
  serialFroozen: "串口连接无响应。",
  notAvailableFlag: "$1功能在当前浏览器中不可用。\r\n请确认$1功能开关已启用。",

  // 积木块相关
  block_delay: "延时",
  seconds: "秒",
  milliseconds: "毫秒",
  microseconds: "微秒",
  to: "至",
  setpin: "设置输出引脚",
  pin: "引脚",
  read_digital_pin: "读取数字输入",
  read_analog_pin: "读取模拟输入",
  show_iot: "在物联网（IoT）标签页显示",
  data: "数值",
  set_rtc: "设置日期和时间",
  get_rtc: "获取日期和时间",
  year: "年",
  month: "月",
  day: "日",
  hour: "时",
  minute: "分",
  second: "秒",
  wifi_scan: "扫描WiFi网络",
  wifi_connect: "连接到WiFi网络",
  wifi_name: "网络名称",
  wifi_key: "密钥/密码",
  easymqtt_start: "启动EasyMQTT（轻量级MQTT协议）",
  easymqtt_publish: "EasyMQTT发布数据",
  topic: "主题",
  session_id: "会话ID",
  file_open: "打开文件",
  file_name: "文件名",
  file_mode: "模式",
  file_binary: "以二进制模式打开",
  file_close: "关闭文件",
  file_write_line: "向文件写入一行内容",
  file_line: "行内容",
  try1: "尝试执行",
  exp1: "捕获异常",
  ntp_sync: "通过NTP（网络时间协议）同步日期和时间",
  timezone: "时区",
  project_info: "项目信息",
  project_info_author: "作者",
  project_info_desc: "描述",
  easymqtt_subscribe: "EasyMQTT订阅主题",
  when: "当",
  data_received: "数据接收时",
  easymqtt_receive: "EasyMQTT接收数据",
  relay: "继电器",
  on: "开启",
  off: "关闭",
  relay_on: "继电器引脚",
  yes: "是",
  no: "否",
  wait_for_data: "等待数据",
  dht_start: "启动DHT传感器",
  dht_measure: "更新DHT11/22传感器读数",
  dht_temp: "获取DHT11/22温度值",
  dht_humi: "获取DHT11/22湿度值",
  type: "类型",

  // 网络相关
  net_http_get: "HTTP GET请求",
  net_http_get_status: "HTTP状态码",
  net_http_get_content: "HTTP响应内容",

  // 启动页
  splash_welcome: "欢迎使用BIPES！",
  splash_footer: "不再显示此页面",
  splash_close: "关闭",
  splash_message: "<p><b>BIPES：嵌入式系统积木块集成开发平台</b> 支持基于积木块和文本的编程方式，适用于多种嵌入式系统和物联网（IoT）模块，兼容MicroPython、CircuitPython、Python或Snek语言。您可通过网络、USB或蓝牙连接、编程、调试和监控各类开发板（兼容列表见<a href=https://bipes.net.br/wp/boards/>https://bipes.net.br/wp/boards/</a>），包括STM32、ESP32、ESP8266、树莓派Pico甚至Arduino。</p><p><b>BIPES</b> 是完全<a href=https://bipes.net.br/wp/development/>开源</a>的HTML/JavaScript项目，无需安装任何软件，支持离线使用！希望BIPES能为您提供帮助，您可通过<a href=https://github.com/BIPES/BIPES/discussions>讨论论坛</a>获取支持、查看<a href=https://github.com/BIPES/BIPES/discussions/categories/announcements>新功能公告</a>，也欢迎提交反馈和建议！</p><p>您可通过以下链接为ESP32/ESP8266刷写MicroPython固件以适配BIPES：<a href=https://bipes.net.br/flash/esp-web-tools/>https://bipes.net.br/flash/esp-web-tools/</a></p><p>感谢使用BIPES！——BIPES开发团队</p>"
};

// 工具箱分类
Blockly.Msg['CAT_TIMING'] = "定时";
Blockly.Msg['CAT_MACHINE'] = "硬件控制";
Blockly.Msg['CAT_DISPLAYS'] = "显示设备";
Blockly.Msg['CAT_SENSORS'] = "传感器";
Blockly.Msg['CAT_OUTPUTS'] = "输出/执行器";
Blockly.Msg['CAT_COMM'] = "通信";
Blockly.Msg['CAT_FILES'] = "文件操作";
Blockly.Msg['CAT_NET'] = "网络与互联网";
Blockly.Msg['CAT_CONTROL'] = "控制流程";